version: "3.9"

services:
  #---------------container--------------
  servicio-mysql-db:
    image: mysql:8.2.0
    restart: always
    container_name: contenedor-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: basededatos1
      MYSQL_ROOT_PASSWORD: PassWord123.

  servicio-postgresql:
    image: postgres:16.1
    restart: always
    container_name: contenedor-postgresql
    ports:
      - "5432:5432"  
    environment:
      POSTGRES_PASSWORD: PassWord123.
      POSTGRES_USER: postgres  
      POSTGRES_DB: basededatos1

  